Add check to avoid border conflict at a bad time for AI Barrad
EaW-Team/equestria_dev pull request #1952
Opened 2023-11-02 12:42 UTC by marius851000

I’ve noticed that Barrad sometimes start border conflict at a very bad time. This add some basic check for them (but it should work with any other border conflict, thought untested). The solution in the base-game is to just not allow AI to do them.

(also, I’m unfamiliar with how this project is managed. A CONTRIBUTING.MD or something might be usefull, but I hope I didn’t missed anything).

Some other notes:
I tried to use the antagonize values, but it seems pretty inconsistant. Griffon Empire consistently have a really high value, far more than wittenland even after it captured most of the territory.
Also, Planned to try some other improvement on Barrad AI, but seeing that there is already a rework on it, I’ll wait.

2023-11-02 16:11 UTC, Yard1 requested changes
Thanks! Left 2 comments.

Vast majority of the contributions are done in-house by a volunteer team coordinating on Discord (discord.gg/equestriaatwar). If you are interested in contributing more, I would highly recommend applying - we are always on the lookout for scripters.

2023-11-02 16:11 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-02 16:11 UTC, Yard1 commented on common/scripted_triggers/AI tools.txt
> +# Will validate if fighting a border war with FROM appear to be a good idea
can we put this into one of the existing files, eg. EAW_triggers?

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 00:42 UTC, Yard1 commented on common/decisions/BAR_decisions.txt
> +				NOT { ai_is_doing_border_war_as_THIS_with_FROM_appropriate = yes }
```suggestion
				ai_is_doing_border_war_as_THIS_with_FROM_appropriate = no
```

2023-11-06 01:00 UTC, Yard1 approved these changes
Thanks for the contribution!

2023-11-06 01:00 UTC, merged

2023-11-06 14:24 UTC, marius851000 commented
Thanks. I have trouble focusing on a single things for too long, and I already have quite a bunch of projets that I need to finish to consider commiting to such a project, but I may reconsider that in the future.